### ISSUE TITLE
Cannot publish the goal as Readme

### ISSUE THREAD

**Issue by ad56583964** [Rayman/turtlebot3_mbf#1]
l just launch three file following Readme, but then meet an error when l use Rviz to publish my 2D Nav Goal.
And the turtlebot cannot move.
![QQ截图20210829071930](https://user-images.githubusercontent.com/20683103/131233316-64d2b0f9-330b-459c-9dc0-f6977cbc462e.png)
![QQ截图20210829071941](https://user-images.githubusercontent.com/20683103/131233317-971c7524-9a59-4427-9c00-ce2c19c9a4be.png)

**Comment by Rayman** [comment]
It seems you are missing the `navfn` package. We should add this to the package.xml so this won't happen anymore.

You can fix it manually with
```sh
sudo apt install ros-$ROS_DISTRO-navfn
```

**Comment by robokamran** [comment]
I have the exact same problem and I have the "navfn" installed. I don't know what could be the source of the problem. I looked at these issues but none were quite helpful :(

https://github.com/magazino/move_base_flex/issues/247
https://github.com/magazino/move_base_flex/issues/247
https://github.com/magazino/move_base_flex/issues/60

I'd appreciate if someone could help us with this.

**Comment by Rayman** [comment]
If you have navfn installed but it can't be found, you probably have a problem in the way your workspace is setup. This isn't a bug in MBF or turtlebot3_mbf.

You could try to print `CMAKE_PREFIX_PATH` to figure out if your overlay is correct. Can you roscd to navfn?

**Comment by robokamran** [comment]
@Rayman Thank you very much for you swift reply and sorry for my delay.

Yes, I can easily do `roscd navfn` and the address is `/opt/ros/noetic/share/navfn`.
Also when I print `CMAKE_PREFIX_PATH` I get this:
`/home/ubuntu/catkin_ws/devel:/opt/ros/noetic`

So what do you think I should do?
Also, I can easily set up MFB using [this tutorial](https://uos.github.io/mbf_docs/tutorials/beginner/basic_navigation/).
But I would be really happy if I could use your scripts!

**Comment by Rayman** [comment]
@robokamran that all looks normal to me. I think I can't help you any further

**Comment by robokamran** [comment]
@Rayman OK, thanks for your help so far. I'll dig more into it to see what's the problem.
